#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const crypto = require("node:crypto");
const os = require("node:os");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

const HOSTING_SERVICES = Object.freeze({
  apex: {
    label: "Apex Hosting",
    defaultFtpPort: 21,
    defaultFtpRoot: "default",
    lifecycle: "panel",
  },
});

const hostedRoot = __dirname;
const projectRoot = path.resolve(__dirname, "../..");
const env = loadEnv();
const command = process.argv[2] || "help";
const args = process.argv.slice(3);
const hostingService = selectedHostingService();

main().catch((error) => {
  console.error(`hosted-services: ${error.message}`);
  process.exit(1);
});

async function main() {
  switch (command) {
    case "build-test-deploy":
      buildTestDeploy();
      break;
    case "deploy":
      deploy();
      break;
    case "upload-jar":
      uploadJar({ build: !args.includes("--skip-build") });
      break;
    case "upload-config":
      uploadConfig();
      break;
    case "status":
      await status();
      break;
    case "rcon-stop":
      await rconStop();
      break;
    case "logs":
    case "log-list":
      logList();
      break;
    case "log-tail":
      logTail();
      break;
    case "log-download":
      logDownload();
      break;
    case "smoke":
      smoke();
      break;
    case "validate":
      await validate();
      break;
    case "print-profile":
      printProfile();
      break;
    case "help":
    case "--help":
    case "-h":
      usage();
      break;
    default:
      usage();
      throw new Error(`Unknown hosted-server command: ${command}`);
  }
}

function buildTestDeploy() {
  console.log(`${hostingService.label} build/test/deploy cycle`);
  console.log("Build and unit tests run locally; the hosted server is the deploy and runtime validation target.");
  deploy();
}

function deploy() {
  uploadJar({ build: !args.includes("--skip-build") });
  uploadConfig();
  console.log("");
  console.log(`${hostingService.label} upload complete.`);
  console.log("Next: start or restart the server from the hosting panel, then run:");
  console.log("  node tools/hosted-services/deploy.js smoke");
}

function uploadJar({ build }) {
  requireFtpConfig();
  const explicitJar = argValue("--jar");
  if (build && !explicitJar) run("Terrascape build", "./gradlew", ["build"]);
  const jar = explicitJar ? releaseCandidateJar(explicitJar) : newestJar();
  console.log(`candidate sha256 ${sha256(jar)}  ${jar}`);
  uploadFile(jar, "mods/" + path.basename(jar));
}

function uploadConfig() {
  const rconPassword = required("TERRASCAPE_RCON_PASSWORD", "Set this to the hosted Terrascape RCON password.");
  const config = [
    `# Generated by tools/hosted-services/deploy.js for ${hostingService.label}.`,
    "http.host=0.0.0.0",
    `http.port=${number("TERRASCAPE_WEB_PORT", 7656)}`,
    `access.mode=${value("TERRASCAPE_ACCESS_MODE", "restricted")}`,
    `access.publicBaseUrl=${publicBaseUrl()}`,
    "rcon.enabled=true",
    "rcon.host=0.0.0.0",
    `rcon.port=${number("TERRASCAPE_RCON_PORT", 6225)}`,
    `rcon.password=${rconPassword}`,
    "rcon.allowRemote=true",
    "validation.smokeTokensEnabled=false",
    "",
  ].join("\n");

  const tmp = path.join(os.tmpdir(), `terrascape-hosted-${process.pid}-${Date.now()}.properties`);
  fs.writeFileSync(tmp, config);
  try {
    uploadFile(tmp, "mods/com.codelabchaos_Terrascape/terrascape.properties", { label: "terrascape.properties" });
  } finally {
    fs.rmSync(tmp, { force: true });
  }
}

function smoke() {
  const rconPassword = required("TERRASCAPE_RCON_PASSWORD", "Set this to the hosted Terrascape RCON password.");
  const host = required("PUBLIC_HOST");
  const webPort = number("TERRASCAPE_WEB_PORT", 7656);
  const rconPort = number("TERRASCAPE_RCON_PORT", 6225);
  run("Hosted runtime smoke", "node", [
    "tools/run-terrascape-runtime-smoke.js",
    "--url",
    `http://${host}:${webPort}`,
    "--rcon-url",
    `http://${host}:${rconPort}`,
  ], {
    env: {
      TERRASCAPE_RCON_PASSWORD: rconPassword,
      TERRASCAPE_MAP_TOKEN: value("TERRASCAPE_MAP_TOKEN", ""),
    },
  });
}

async function validate() {
  await status();
  console.log("");
  smoke();
  console.log("");
  try {
    logTail();
  } catch (error) {
    console.error(`log-tail skipped: ${error.message}`);
  }
}

async function status() {
  const health = await rconRequest("/health", { method: "GET", authorize: false });
  console.log(`${hostingService.label} Terrascape RCON ${health.status === 200 ? "UP" : "DOWN"} ${rconBaseUrl()}`);
  console.log(health.text);
}

async function rconStop() {
  const response = await rconRequest("/command", {
    method: "POST",
    authorize: true,
    body: JSON.stringify({ command: "stop" }),
  });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(`RCON stop failed with HTTP ${response.status}: ${response.text}`);
  }
  console.log(response.text);
  console.log(`${hostingService.label} server stop requested. Start it again from the hosting panel after FTP upload.`);
}

function logList() {
  const logs = listRemoteLogs();
  if (!logs.length) {
    console.log(`No logs found under ${remoteLogDir()}/`);
    return;
  }
  for (const log of logs) {
    console.log(log);
  }
}

function logTail() {
  const lines = argNumber(["--lines", "-n"], 160);
  const latest = latestRemoteLog();
  const local = downloadRemoteLog(latest);
  const text = fs.readFileSync(local, "utf8");
  const tail = text.split(/\r?\n/).slice(-lines).join("\n");
  console.log(`# ${latest}`);
  console.log(tail);
}

function logDownload() {
  const logs = listRemoteLogs();
  if (!logs.length) {
    console.log(`No logs found under ${remoteLogDir()}/`);
    return;
  }
  const outDir = path.join(hostedRoot, "logs");
  fs.mkdirSync(outDir, { recursive: true });
  for (const log of logs) {
    downloadRemoteLog(log, outDir);
  }
  console.log(`downloaded ${logs.length} log(s) to ${outDir}`);
}

function printProfile() {
  console.log("Hosted Terrascape validation profile");
  console.log(`service: ${hostingService.id} (${hostingService.label})`);
  console.log(`game:    ${required("GAME_HOST")}:${number("GAME_PORT", 25565)}`);
  console.log(`web:     http://${required("PUBLIC_HOST")}:${number("TERRASCAPE_WEB_PORT", 7656)}`);
  console.log(`maplink: ${publicBaseUrl()}`);
  console.log(`rcon:    http://${required("PUBLIC_HOST")}:${number("TERRASCAPE_RCON_PORT", 6225)}`);
  console.log(`ftp:     ${required("FTP_USER")}@${required("FTP_HOST")}:${number("FTP_PORT", hostingService.defaultFtpPort)}`);
  console.log(`root:    ${ftpRoot() || "/"}`);
  console.log(`mode:    access=${value("TERRASCAPE_ACCESS_MODE", "restricted")}, mapToken=${value("TERRASCAPE_MAP_TOKEN", "") ? "set" : "not set"}`);
  console.log(`start:   ${hostingService.lifecycle}`);
}

function listRemoteLogs() {
  const output = ftpRead(remoteLogDir() + "/");
  return output.split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map(parseListEntryName)
    .filter((name) => name && /\.(log|txt)$/i.test(name))
    .sort();
}

function parseListEntryName(line) {
  if (!line) return null;
  const parts = line.split(/\s+/);
  return parts[parts.length - 1];
}

function latestRemoteLog() {
  const logs = listRemoteLogs();
  if (!logs.length) throw new Error(`No logs found under ${remoteLogDir()}/`);
  return logs[logs.length - 1];
}

function downloadRemoteLog(logName, outDir = path.join(hostedRoot, "logs")) {
  fs.mkdirSync(outDir, { recursive: true });
  const local = path.join(outDir, logName);
  ftpDownload(remoteLogDir() + "/" + logName, local);
  return local;
}

function remoteLogDir() {
  return value("LOG_DIR", "logs").replace(/^\/+|\/+$/g, "");
}

async function rconRequest(pathname, options) {
  const url = rconBaseUrl() + pathname;
  const headers = {};
  if (options.body) headers["Content-Type"] = "application/json";
  if (options.authorize) headers["X-SynthRCON-Token"] = required("TERRASCAPE_RCON_PASSWORD");
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10000);
  try {
    const response = await fetch(url, {
      method: options.method || "GET",
      headers,
      body: options.body,
      signal: controller.signal,
    });
    return { status: response.status, text: await response.text() };
  } catch (error) {
    if (error.name === "AbortError") {
      throw new Error(`${url} timed out after 10000ms`);
    }
    throw new Error(`${url} is unreachable: ${error.message}`);
  } finally {
    clearTimeout(timeout);
  }
}

function rconBaseUrl() {
  return `http://${required("PUBLIC_HOST")}:${number("TERRASCAPE_RCON_PORT", 6225)}`;
}

function publicBaseUrl() {
  const explicit = value("TERRASCAPE_PUBLIC_BASE_URL", "");
  if (explicit) return explicit.replace(/\/+$/, "");
  return `http://${required("PUBLIC_HOST")}:${number("TERRASCAPE_WEB_PORT", 7656)}`;
}

function uploadFile(localPath, remotePath, options = {}) {
  const { host, port, user, password } = requireFtpConfig();
  const remoteUrl = ftpUrl(host, port, remotePath);
  const label = options.label || path.basename(localPath);
  console.log(`\n== ${hostingService.label} FTP upload ${label}`);
  console.log(`$ curl --ftp-create-dirs --upload-file ${localPath} ${redactFtpUrl(remoteUrl)}`);
  const res = spawnSync("curl", [
    "--fail",
    "--show-error",
    "--silent",
    "--ftp-create-dirs",
    "--user",
    `${user}:${password}`,
    "--upload-file",
    localPath,
    remoteUrl,
  ], { cwd: projectRoot, encoding: "utf8" });
  if (res.status !== 0) {
    throw new Error(`FTP upload failed for ${remotePath}: ${(res.stderr || res.stdout || "").trim()}`);
  }
  console.log(`uploaded ${path.basename(localPath)} -> ${remotePath}`);
}

function ftpRead(remotePath) {
  const { host, port, user, password } = requireFtpConfig();
  const remoteUrl = ftpUrl(host, port, remotePath);
  const res = spawnSync("curl", [
    "--fail",
    "--show-error",
    "--silent",
    "--list-only",
    "--user",
    `${user}:${password}`,
    remoteUrl,
  ], { cwd: projectRoot, encoding: "utf8" });
  if (res.status !== 0) {
    throw new Error(`FTP read failed for ${remotePath}: ${(res.stderr || res.stdout || "").trim()}`);
  }
  return res.stdout || "";
}

function ftpDownload(remotePath, localPath) {
  const { host, port, user, password } = requireFtpConfig();
  const remoteUrl = ftpUrl(host, port, remotePath);
  console.log(`download ${remotePath} -> ${localPath}`);
  const res = spawnSync("curl", [
    "--fail",
    "--show-error",
    "--silent",
    "--user",
    `${user}:${password}`,
    "--output",
    localPath,
    remoteUrl,
  ], { cwd: projectRoot, encoding: "utf8" });
  if (res.status !== 0) {
    throw new Error(`FTP download failed for ${remotePath}: ${(res.stderr || res.stdout || "").trim()}`);
  }
}

function requireFtpConfig() {
  return {
    host: required("FTP_HOST"),
    port: number("FTP_PORT", hostingService.defaultFtpPort),
    user: required("FTP_USER"),
    password: required("FTP_PASSWORD", `Set this to the ${hostingService.label} FTP password.`),
  };
}

function ftpUrl(host, port, remotePath) {
  const root = ftpRoot();
  const cleanRemote = remotePath.replace(/^\/+/, "");
  const fullPath = [root, cleanRemote].filter(Boolean).join("/");
  return `ftp://${host}:${port}/${fullPath}`;
}

function ftpRoot() {
  return value("FTP_ROOT", hostingService.defaultFtpRoot || "").replace(/^\/+|\/+$/g, "");
}

function redactFtpUrl(url) {
  return url.replace(/^ftp:\/\/([^@/]+@)?/, "ftp://");
}

function newestJar() {
  const dir = path.join(projectRoot, "build", "libs");
  const matches = fs.readdirSync(dir)
    .filter((name) => /^Terrascape-.*\.jar$/.test(name) && !name.endsWith("-plain.jar"))
    .map((name) => {
      const full = path.join(dir, name);
      return { full, mtime: fs.statSync(full).mtimeMs };
    })
    .sort((a, b) => b.mtime - a.mtime);
  if (!matches.length) throw new Error(`No Terrascape jar found in ${dir}; run ./gradlew build first.`);
  return matches[0].full;
}

function releaseCandidateJar(input) {
  const jar = path.resolve(projectRoot, input);
  if (!fs.existsSync(jar) || !fs.statSync(jar).isFile()) {
    throw new Error(`Release candidate jar does not exist: ${jar}`);
  }
  if (!/^Terrascape-.+\.jar$/.test(path.basename(jar)) || jar.endsWith("-plain.jar")) {
    throw new Error(`Release candidate must be a Terrascape-<version>.jar: ${jar}`);
  }
  return jar;
}

function sha256(file) {
  return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");
}

function run(label, commandName, commandArgs, options = {}) {
  console.log(`\n== ${label}`);
  console.log(`$ ${[commandName, ...commandArgs].join(" ")}`);
  const res = spawnSync(commandName, commandArgs, {
    cwd: projectRoot,
    stdio: "inherit",
    shell: false,
    env: { ...process.env, ...(options.env || {}) },
  });
  if (res.status !== 0) throw new Error(`${label} failed with exit code ${res.status}`);
}

function loadEnv() {
  const result = { ...process.env };
  const file = process.env.HOSTING_ENV_FILE || path.join(hostedRoot, "hosted-server.env");
  if (!fs.existsSync(file)) return result;
  for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const parsed = parseEnvLine(line);
    if (parsed && result[parsed.key] === undefined) result[parsed.key] = parsed.value;
  }
  return result;
}

function parseEnvLine(raw) {
  const line = raw.trim();
  if (!line || line.startsWith("#")) return null;
  const eq = line.indexOf("=");
  if (eq <= 0) return null;
  const key = line.slice(0, eq).trim();
  let parsedValue = line.slice(eq + 1).trim();
  if ((parsedValue.startsWith('"') && parsedValue.endsWith('"')) || (parsedValue.startsWith("'") && parsedValue.endsWith("'"))) {
    parsedValue = parsedValue.slice(1, -1);
  }
  return { key, value: parsedValue };
}

function value(name, fallback = "") {
  const raw = env[`HOSTING_${name}`];
  return raw == null || String(raw).trim() === "" ? fallback : String(raw).trim();
}

function required(name, hint = null) {
  const raw = value(name, "");
  if (!raw) throw new Error(`Missing HOSTING_${name}.${hint ? ` ${hint}` : ""}`);
  return raw;
}

function number(name, fallback) {
  const parsed = Number.parseInt(value(name, String(fallback)), 10);
  if (!Number.isInteger(parsed) || parsed <= 0) throw new Error(`HOSTING_${name} must be a positive integer.`);
  return parsed;
}

function boolString(name, fallback) {
  const raw = value(name, String(fallback));
  return /^(1|true|yes|on|enabled)$/i.test(raw) ? "true" : "false";
}

function selectedHostingService() {
  const id = value("SERVICE", "apex").toLowerCase();
  const service = HOSTING_SERVICES[id];
  if (!service) {
    throw new Error(`Unsupported HOSTING_SERVICE "${id}". Supported values: ${Object.keys(HOSTING_SERVICES).join(", ")}`);
  }
  return { id, ...service };
}

function argNumber(names, fallback) {
  for (let i = 0; i < args.length; i++) {
    if (names.includes(args[i])) {
      const parsed = Number.parseInt(args[i + 1], 10);
      if (!Number.isInteger(parsed) || parsed <= 0) throw new Error(`${args[i]} requires a positive integer.`);
      return parsed;
    }
  }
  return fallback;
}

function argValue(name) {
  const index = args.indexOf(name);
  if (index < 0) return null;
  const result = args[index + 1];
  if (!result || result.startsWith("--")) throw new Error(`${name} requires a value.`);
  return result;
}

function usage() {
  console.log(`Usage:
  node tools/hosted-services/deploy.js print-profile
  node tools/hosted-services/deploy.js build-test-deploy
  node tools/hosted-services/deploy.js deploy [--skip-build | --jar PATH]
  node tools/hosted-services/deploy.js upload-jar [--skip-build | --jar PATH]
  node tools/hosted-services/deploy.js upload-config
  node tools/hosted-services/deploy.js status
  node tools/hosted-services/deploy.js rcon-stop
  node tools/hosted-services/deploy.js log-list
  node tools/hosted-services/deploy.js log-tail [-n N]
  node tools/hosted-services/deploy.js log-download
  node tools/hosted-services/deploy.js smoke
  node tools/hosted-services/deploy.js validate

Required local file:
  cp tools/hosted-services/hosted-server.env.example tools/hosted-services/hosted-server.env

Notes:
  - HOSTING_SERVICE is a typed provider selector. Supported values: ${Object.keys(HOSTING_SERVICES).join(", ")}.
  - build-test-deploy runs the Gradle build/tests locally, then uploads to the hosted server.
  - --jar uploads an explicit Actions-built release candidate without rebuilding it.
  - FTP upload cannot start a hosted server. Stop/start from the hosting panel.
  - validate uses RCON and the web API after the panel has started the server.
`);
}
